### ISSUE TITLE
generate duplicate styling code

### ISSUE THREAD

**Issue by bigopon** [rtsao/csjs#27]
Hi,

When I use csjs on
```javascript
var style = csjs`
.a { float: right }
`
```
I get the result
```javascript
var _templateObject = _taggedTemplateLiteral(["\n.a { float: right }\n"], ["\n.a { float: right }\n"]);

	function _taggedTemplateLiteral(strings, raw) {
		return Object.freeze(Object.defineProperties(strings, {
			raw: {
				value: Object.freeze(raw)
			}
		}));
	}

	var style = csjs(_templateObject);
```

I'm not sure if it's only me.

**Comment by rtsao** [comment]
I'm not quite sure what the issue is, that's just how Babel transpiles tagged template strings. For example: https://babeljs.io/repl/#?evaluate=true&presets=es2015&experimental=true&loose=false&spec=false&playground=false&code=function%20foo()%20%7B%0A%20%20console.log(arguments)%3B%0A%7D%0A%0Avar%20bar%20%3D%20foo%60hello%20world%60%3B

**Comment by bigopon** [comment]
Ok thanks then. I'll close this
