### ISSUE TITLE
loading fonts?

### ISSUE THREAD

**Issue by contra** [rtsao/csjs#40]
How would this work with csjs/csjs-inject? Doesn't look like anyone has tried this yet.

**Comment by rtsao** [comment]
`@font-face` should work normally as it would in CSS, but I think maybe you're getting at a couple of things:

1) Flash of unstyled text
This is basically unavoidable with csjs-inject. If your styles are known at build-time, one option is to use csjs-extractify and serve up plain CSS. Alternatively, you could use [csjs-styletron](https://github.com/rtsao/csjs-styletron) which is essentially a better version of csjs-inject that also supports server-side *render*-time extraction of CSS. So if you are doing server-rendering, you can serve up the needed styles as an inline CSS element which should help reduce FOUC. I haven't had a chance to document it that module yet, but it works and [styletron](https://github.com/rtsao/styletron) itself is pretty mature. I think csjs-styletron is probably the best approach (in conjunction with server-rendering) since it doesn't require any buildtime tooling but still can provided nice prerendered initial pageloads.

2) Scoping of fonts
It seems to me fonts are sort of a global resource so I haven't really looked into it.

But generally, I think because fonts are typically completely static for an app and rarely change, it's best to put all the font-related CSS on a CDN and just stick it in the static document template in the `<head>`.

**Comment by contra** [comment]
Thanks for the info! I'm sure people will find this useful.
